### ISSUE TITLE
Can't install on PHP 8.1

### ISSUE THREAD

**Issue by lurkalot** [coppermine-gallery/cpg1.7.x#1]
I have CPG 1.7.01 installed now but had to roll my local back to php 7.4 before it would install.  If I'm reading this correctly the installer tests GD2 on step 5 and the functions used in the installer are dead in php 8.0 onwards. https://www.php.net/manual/en/function.imagedestroy.php

So same would apply when installing CPG 1.6.x as that wouldn't install on my local either until I switched to php 7.4

**Comment by ron4mac** [comment]
Hmmm! How did that escape scrutiny? Will look into correcting it ASAP.

**Comment by ron4mac** [comment]
Corrected one old line of bad code that only PHP 8.1+ can't ignore.
Thanks for the feedback here on Github.
(same correction done for 1.6.24)

**Comment by lurkalot** [comment]
Thank you ron4mac, it Installs nicely on 8.1 now.
